WebTask/Models/Employee.cs
using System;
using System.Collections.Generic;

namespace WebTask.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Age { get; set; }
        public string Speciality { get; set; }
        public DateTime EmployementDate { get; set; }
        public string ImagePath { get; set; }
        public virtual ICollection<Task> ListOfTasks { get; set; }
    }
}

WebTask/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTask.Models;
using WebTask.Models.Exceptions;
using WebTask.Services;

namespace WebTask.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ILogger<EmployeesController> _logger;
        private readonly ApplicationContext _context;
        private readonly EmployeesService _employeesService;
        private readonly UsersService _usersService;

        public EmployeesController(ILogger<EmployeesController> logger, ApplicationContext context, EmployeesService employeesService, UsersService usersService)
        {
            _logger = logger;
            _context = context;
            _employeesService = employeesService;
            _usersService = usersService;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            IEnumerable<Employee> employees = await _employeesService.GetAllAsync();
            ViewBag.Specialitys = employees.Select(e => e.Speciality).Distinct();
            return View(employees);
        }

        // GET: Employees/Search?name=&age=&date=&commit=Search
        public async Task<IActionResult> Search(string name, string speciality, int? age, DateTime employementDate)
        {
            ViewBag.Specialitys = (await _employeesService.GetAllAsync()).Select(e => e.Speciality).Distinct();
            return View("Index", await _employeesService.SearchAsync(name, speciality, age, employementDate));
        }

        // GET: Employees/PersonalPage
        public async Task<IActionResult> PersonalPage()
        {
            var employee = await _usersService.GetEmployeeAsync(HttpContext.User.Identity.Name);
            return RedirectToAction("Details", new { id = employee.Id});
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdIncludeTasksAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeesService.AddAsync(employee);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException)
            {
                return NotFound();
            }
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _employeesService.UpdateAsync(employee);
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            try
            {
                await _employeesService.DeleteById(id);
                return RedirectToAction(nameof(Index));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }
    }
}

WebTask/Controllers/TasksController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTask.Models;
using WebTask.Models.Exceptions;
using WebTask.Services;

namespace WebTask.Controllers
{
    public class TasksController : Controller
    {
        private readonly ILogger<TasksController> _logger;
        private TasksService _taskService;
        private EmployeesService _employeesService;

        public TasksController(ILogger<TasksController> logger, TasksService tasksService, EmployeesService employeesService)
        {
            _logger = logger; 
            _taskService = tasksService;
            _employeesService = employeesService;

        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                return View(await _taskService.GetByIdAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // GET: Tasks/Create
        public async Task<IActionResult> Create(int? id)
        {
            try
            {
                ViewBag.EmployeeId = (await _employeesService.GetByIdAsync(id)).Id;
                return View();
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,CompletionDate")] Models.Task task, int? employeeId)
        {
            ViewBag.EmployeeId = employeeId;
            if (ModelState.IsValid)
            {
                try
                {
                    await _taskService.CreateAsync(task, employeeId);
                    return RedirectToAction("Details", "Employees", new { id = employeeId });
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    return NotFound();
                }
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                return View(await _taskService.GetByIdAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CompletionDate,EmployeeId")] Models.Task task)
        {
            if (id != task.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _taskService.UpdateAsync(task);
                    return RedirectToAction("Details", "Employees", new { id = task.EmployeeId });
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    return NotFound();
                }
            }
            return View(task);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                return View(await _taskService.GetByIdAsync(id));
            }
            catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            try
            {
                Employee employee = await _taskService.GetEmployee(id);
                await _taskService.DeleteById(id);
                return RedirectToAction("Details", "Employees", new { id = employee.Id });
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }        
    }
}

WebTask/Views/Employees/Create.cshtml
@model WebTask.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speciality" class="control-label"></label>
                <input asp-for="Speciality" class="form-control" />
                <span asp-validation-for="Speciality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployementDate" class="control-label"></label>
                <input type="date" asp-for="EmployementDate" class="form-control" />
                <span asp-validation-for="EmployementDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebTask/Views/Employees/Delete.cshtml
@model WebTask.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Speciality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Speciality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployementDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployementDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark">No</a>
    </form>
</div>

WebTask/Views/Employees/Details.cshtml
@model WebTask.Models.Employee

@{
    ViewData["Title"] = "Personal Page";
}

<h1>Personal Page</h1>

<div>
    <h4>@Model.Name</h4>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-dark">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-4"><img class="rounded-img big-avatar" src="~/avatars/@Model.ImagePath" /></div>
        <div class="col-sm-8">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Age)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Age)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Speciality)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Speciality)
                </dd>
                <dt class="col-sm-2">
                    Employement Date
                </dt>
                <dd class="col-sm-10">
                    @Model.EmployementDate.ToShortDateString()
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <h2>Tasks:</h2>
    <div>
        <a asp-route-id="@Model.Id" asp-controller="Tasks" asp-action="Create" class="btn btn-primary">Add task</a>
    </div>
    <br />
    <div class="row">
        @if (Model.ListOfTasks.Count == 0)
        {
            <div class="container">
                <p>No tasks for this user.</p>
            </div>
        }
        else
        {
            @foreach (WebTask.Models.Task task in Model.ListOfTasks)
            {
                <div class="col-sm-4">
                    <div class="card">
                        <h5 class="card-header">@task.CompletionDate.ToShortDateString()</h5>
                        <div class="card-body">
                            <h5 class="card-title">@task.Name</h5>
                            <p class="card-text">@task.Description</p>
                            <a asp-controller="Tasks" asp-action="Delete" asp-route-id="@task.Id" class="btn btn-danger">Delete</a>
                            <a asp-controller="Tasks" asp-action="Edit" asp-route-id="@task.Id" class="btn btn-dark">Edit</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

WebTask/Views/Employees/Edit.cshtml
@model WebTask.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speciality" class="control-label"></label>
                <input asp-for="Speciality" class="form-control" />
                <span asp-validation-for="Speciality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployementDate" class="control-label"></label>
                <input type="date" asp-for="EmployementDate" class="form-control" />
                <span asp-validation-for="EmployementDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebTask/Views/Employees/Index.cshtml
@model IEnumerable<WebTask.Models.Employee>
@{
    ViewData["Title"] = "Home";
}
<!DOCTYPE html>

<html>
<head>
    <title>Employees</title>
</head>
<body>
    <h3>Employees</h3>
    <form asp-action="Search" method="get" class="row search-form">
        <div class="col-sm-3">
            <input type="text" name="name" placeholder="name" class="form-control">
        </div>
        <div class="col-sm-3">
            <select name="speciality" class="form-control" required>
                <option selected disabled>select speciality</option>
                @foreach (string speciality in ViewBag.Specialitys)
                {
                    <option>@speciality</option>
                }
            </select>
        </div>
        <div class="col-sm-2">
            <input type="number" name="age" placeholder="age" class="form-control">
        </div>
        <div class="col-sm-2">
            <input type="date" name="employementDate" placeholder="Employement Date" class="form-control" />
        </div>
        <div class="col-sm-2">
            <input type="submit" name="commit" value="Search" class="btn btn-primary btn-block">
        </div>
    </form>
    <div>
        <a asp-action="Create" asp-controller="Employees" class="btn btn-primary">Add</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Speciality</th>
                <th scope="col">Age</th>
                <th scope="col">Employement Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model)
            {
                <tr>
                    <td><img class="avatar rounded-img" src="~/avatars/@employee.ImagePath" /></td>
                    <td><a href="/Employees/Details/@employee.Id">@employee.Name</a></td>
                    <td>@employee.Speciality</td>
                    <td>@employee.Age</td>
                    <td>@employee.EmployementDate.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>