WebTask/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTask.Models;
using WebTask.Models.Exceptions;
using WebTask.Services;

namespace WebTask.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ILogger<EmployeesController> _logger;
        private readonly ApplicationContext _context;
        private readonly EmployeesService _employeesService;
        private readonly UsersService _usersService;

        public EmployeesController(ILogger<EmployeesController> logger, ApplicationContext context, EmployeesService employeesService, UsersService usersService)
        {
            _logger = logger;
            _context = context;
            _employeesService = employeesService;
            _usersService = usersService;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            IEnumerable<Employee> employees = await _employeesService.GetAllAsync();
            ViewBag.Specialitys = employees.Select(e => e.Speciality).Distinct();
            return View(employees);
        }

        // GET: Employees/Search?name=&age=&date=&commit=Search
        public async Task<IActionResult> Search(string name, string speciality, int? age, DateTime employementDate)
        {
            ViewBag.Specialitys = (await _employeesService.GetAllAsync()).Select(e => e.Speciality).Distinct();
            return View("Index", await _employeesService.SearchAsync(name, speciality, age, employementDate));
        }

        // GET: Employees/PersonalPage
        public async Task<IActionResult> PersonalPage()
        {
            var employee = await _usersService.GetEmployeeAsync(HttpContext.User.Identity.Name);
            return RedirectToAction("Details", new { id = employee.Id});
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdIncludeTasksAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeesService.AddAsync(employee);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException)
            {
                return NotFound();
            }
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _employeesService.UpdateAsync(employee);
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            try
            {
                await _employeesService.DeleteById(id);
                return RedirectToAction(nameof(Index));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }
    }
}

WebTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        
    }
}

WebTask/Views/Home/Index.cshtml
@model IEnumerable<WebTask.Models.Employee>
@{
    ViewData["Title"] = "Home";
}
<!DOCTYPE html>

<html>
<head>
    <title>Employees</title>
</head>
<body>
    <h3>Employees</h3>
    <form class="row search-form">
        <div class="col-sm-4">
            <input type="text" name="name" placeholder="name" class="form-control">
        </div>
        <div class="col-sm-3">
            <select name="speciality" class="form-control">
                <option selected disabled>select speciality</option>
            </select>
        </div>
        <div class="col-sm-2">
            <input type="number" name="age" placeholder="age" class="form-control">
        </div>
        <div class="col-sm-2">
            <input type="submit" name="commit" value="Search" class="btn btn-primary btn-block">
        </div>
    </form>
    <div>
        <a asp-action="Create" asp-controller="Employees" class="btn btn-primary">Create New</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Speciality</th>
                <th scope="col">Age</th>
                <th scope="col">Employement Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model)
            {
                <tr>
                    <td><img class="avatar rounded-img" src="~/avatars/@employee.ImagePath" /></td>
                    <td><a href="/Employees/Details/@employee.Id">@employee.Name</a></td>
                    <td>@employee.Speciality</td>
                    <td>@employee.Age</td>
                    <td>@employee.EmployementDate</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

WebTask/Views/Home/PersonalPage.cshtml
@model WebTask.Models.Employee

@{
    ViewData["Title"] = "PersonalPage";
}

<h1>PersonalPage</h1>

<div>
    <h4>@Model.Name</h4>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-4"><img class="rounded-img big-avatar img-fluid" src="~/avatars/@Model.ImagePath" /></div>
        <div class="col-sm-8">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Age)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Age)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Speciality)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Speciality)
                </dd>
                <dt class="col-sm-2">
                    Employement Date
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.EmployementDate)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <h2>Tasks:</h2>
    <div class="row">
        @if (Model.ListOfTasks.Count == 0)
        {
            <div class="container">
                <p>No tasks for this user.</p>
            </div>
        }
        else
        {
            @foreach (WebTask.Models.Task task in Model.ListOfTasks)
            {
                <div class="col-sm-4">
                    <div class="card bg-light" style="max-width: 18rem;">
                        <div class="card-header">@task.CompletionDate</div>
                        <div class="card-body">
                            <h5 class="card-title">@task.Name</h5>
                            <p class="card-text">@task.Description</p>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>