WebTask/Controllers/AuthenticationController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTask.Models;
using WebTask.Models.Exceptions;
using WebTask.Services;

namespace WebTask.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly ILogger<AuthenticationController> _logger;
        private UsersService _usersService;

        public AuthenticationController(ILogger<AuthenticationController> logger, UsersService usersService)
        {
            _logger = logger;
            _usersService = usersService;

        }

        // GET: Authentication/Authenticate
        [HttpGet]
        public IActionResult Authenticate()
        {
            return View();
        }

        // POST: Authentication/Authenticate
        [HttpPost]
        public async Task<IActionResult> Authenticate([Bind("Login, Password")] AuthenticateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User user = await _usersService.GetAsync(model.Login, model.Password);
                    string tokenHandler = _usersService.GetJwt(user);
                    HttpContext.Session.SetString("JWToken", tokenHandler);
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    ViewBag.ErrorMessage = ex.Message;
                    return View();
                }
               
                return RedirectToAction("Index", "Employees");
            }
            return View();
        }


        /// <summary>
        /// Logout user. Clear the session.
        /// </summary>
        /// <returns>Redirection to Index() of EmployeesController</returns>
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Employees");
        }
    }
}

WebTask/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTask.Models;
using WebTask.Models.Exceptions;
using WebTask.Services;

namespace WebTask.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ILogger<EmployeesController> _logger;
        private readonly ApplicationContext _context;
        private readonly EmployeesService _employeesService;
        private readonly UsersService _usersService;

        public EmployeesController(ILogger<EmployeesController> logger, ApplicationContext context, EmployeesService employeesService, UsersService usersService)
        {
            _logger = logger;
            _context = context;
            _employeesService = employeesService;
            _usersService = usersService;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            IEnumerable<Employee> employees = await _employeesService.GetAllAsync();
            ViewBag.Specialitys = employees.Select(e => e.Speciality).Distinct();
            return View(employees);
        }

        // GET: Employees/Search?name=&age=&date=&commit=Search
        public async Task<IActionResult> Search(string name, string speciality, int? age, DateTime employementDate)
        {
            ViewBag.Specialitys = (await _employeesService.GetAllAsync()).Select(e => e.Speciality).Distinct();
            return View("Index", await _employeesService.SearchAsync(name, speciality, age, employementDate));
        }

        // GET: Employees/PersonalPage
        public async Task<IActionResult> PersonalPage()
        {
            var employee = await _usersService.GetEmployeeAsync(HttpContext.User.Identity.Name);
            return RedirectToAction("Details", new { id = employee.Id});
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdIncludeTasksAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeesService.AddAsync(employee);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException)
            {
                return NotFound();
            }
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Speciality,EmployementDate,ImagePath")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _employeesService.UpdateAsync(employee);
                } catch (RepositoryException ex)
                {
                    _logger.LogError(ex.Message, ex);
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                return View(await _employeesService.GetByIdAsync(id));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            try
            {
                await _employeesService.DeleteById(id);
                return RedirectToAction(nameof(Index));
            } catch (RepositoryException ex)
            {
                _logger.LogError(ex.Message, ex);
                return NotFound();
            }
        }
    }
}

WebTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">WebTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <div>
                    @if (Context.User.Identity.Name == null)
                    {
                        <a asp-controller="Authentication" , asp-action="Authenticate">Login</a>
                    }
                    else
                    {
                        <a asp-controller="Employees" asp-action="PersonalPage">@Context.User.Identity.Name</a><a> | </a>
                        <a asp-controller="Authentication" asp-action="Logout">Logout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>